# Generated by Django 5.1.6 on 2025-02-08 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viatge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destinacio', models.CharField(max_length=100)),
                ('data_inici', models.DateField()),
                ('data_fi', models.DateField()),
                ('descripcio', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viatges', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
