# Generated by Django 5.1.3 on 2025-03-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatge',
            name='descripcio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
