# Generated by Django 5.1.3 on 2025-03-17 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_viatge_descripcio'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatge',
            name='continent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='viatge',
            name='pais',
            field=models.TextField(blank=True, null=True),
        ),
    ]
