# Generated by Django 5.1.3 on 2025-03-17 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_viatge_continent_viatge_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viatge',
            name='continent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='viatge',
            name='pais',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
