# Generated by Django 5.1.3 on 2025-03-17 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_viatge_continent_alter_viatge_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinacio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('pais', models.CharField(max_length=50)),
                ('continent', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='viatge',
            name='continent',
        ),
        migrations.RemoveField(
            model_name='viatge',
            name='pais',
        ),
        migrations.AlterField(
            model_name='viatge',
            name='destinacio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viatges', to='accounts.destinacio'),
        ),
    ]
