# Generated by Django 5.1.3 on 2025-04-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_destinacio_remove_viatge_continent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viatge',
            name='num_persones',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
